/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "outline": "#76777d",
        "on-secondary-fixed": "#00201d",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#b9c7e0",
        "tertiary": "#000000",
        "primary-fixed-dim": "#bec6e0",
        "on-surface-variant": "#45464d",
        "tertiary-container": "#0d1c2f",
        "on-secondary-fixed-variant": "#005049",
        "surface-container": "#eceef0",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#3a485c",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed": "#d5e3fd",
        "on-primary-container": "#7c839b",
        "on-background": "#191c1e",
        "secondary-fixed-dim": "#6bd8cb",
        "on-primary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
        "background": "#f7f9fb",
        "primary": "#000000",
        "secondary": "#006a61",
        "primary-container": "#131b2e",
        "surface-container-low": "#f2f4f6",
        "surface-dim": "#d8dadc",
        "surface": "#f7f9fb",
        "secondary-container": "#86f2e4",
        "inverse-on-surface": "#eff1f3",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dae2fd",
        "outline-variant": "#c6c6cd",
        "on-surface": "#191c1e",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-container-high": "#e6e8ea",
        "inverse-primary": "#bec6e0",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#89f5e7",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-container": "#006f66",
        "on-tertiary-container": "#76859b",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#0d1c2f",
        "surface-tint": "#565e74"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-mobile": "16px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "unit": "8px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "gutter": "24px"
      },
      "fontFamily": {
        "h2": ["Public Sans"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "data-mono": ["Inter"],
        "body-lg": ["Inter"],
        "h3": ["Public Sans"],
        "h1": ["Public Sans"],
        "label-caps": ["Inter"]
      },
      "fontSize": {
        "h2": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "data-mono": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "h3": ["24px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600"}],
        "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
